### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basileLeroy** [FundaErmete/SASS#1]
# Feedback

## Technical
When using SCSS, it is important to use nesting (this is one of the main features of SCSS)
```scss
body {
    section {
        pre {
            ...
        }
    }
}
```
except for **variables, mixin's and imports** everything should be inside the `body{...}` selector in your scss files.

Using variables and mixins means that repetition is minimalized. make sure to not have code that can be replaced by your variables or mixins.

You are also missing your math operator from the exercise, where you had to muliply the padding * 2 on a certain element.

In your **blue.scss** and **red.scss** you copied almost the full content of the **style.scss** but with SCSS, it not needed to do that. You can just import your style.scss and only overwrite certain elements like in the example below:
```scss
// Example BLUE.SCSS file
@use 'style';

body {
    h1,h4,h6 {
        color: blue;
    }
    pre {
        color: blue;
    }
}
```

## GIT
I can only see your first commit, next time, make sure to commit more frequently. Generally I recommend to either commit 5-10 times a day or to commit per feature.

Have a look at our [GIT - Best Practises](https://github.com/becodeorg/GNT-Verou-5/blob/main/1.The-Field/05.Git/best-practises.md)
